version: '3'
services:
  app:
    container_name: job-search
    restart: always
    build: .
    ports:
      - '4000:4000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  react:
    container_name: job-search-react
    restart: always
    build: .
    ports:
      - '4000:4000'
    external_links:
      - mongo
